name: Auto-Approve PR

on:
  pull_request:
    types: [submitted, synchronize, reopened] # Trigger on PR submission, sync, and reopen

jobs:
  auto-approve:
    runs-on: ubuntu-latest
    permissions:
      checks: read
    steps:
      - name: Wait for GitHub Checks
        uses: poseidon/wait-for-status-checks@v0.6.0
        with:
          token: ${{ secrets.GITHUB_TOKEN }}

