name: Auto-Approve PR

on:
  pull_request:
    types: [opened, synchronize, reopened] # Trigger on PR submission, sync, and reopen

jobs:
  auto-approve:
    runs-on: ubuntu-latest
    permissions:
      checks: read
      pull-requests: write
    steps:
      - name: Wait for GitHub Checks
        uses: poseidon/wait-for-status-checks@v0.6.0
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
      - name: Auto Approve
        uses: hmarr/auto-approve-action@v4

