name: Test Airflow DAGs

on:
  push:
    branches:
      - feature/new

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.12' #Adjust version as needed.
          
      - name: Lint SQL with SQLFluff
        run: |
          pip install sqlfluff==0.9.1 click==8.0.3
          pushd sql || exit
          sqlfluff lint \
            --dialect bigquery \
            --ignore parsing,templating \
            --format github-annotation \
            --disable_progress_bar \
            sql_bigquery/ || exit 1
          popd || exit
