name: Test Airflow DAGs

on:
  push:
    branches:
      - feature/dagbag2
    paths:
      - "src/python/cloud_composer/dags/**"

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.12' #Adjust version as needed.

      - name: Install dependencies
        run: |
          pip install apache-airflow
          pip install pytest

      - name: Test airflow DAGs
        run: |
          pushd src/python/cloud_composer/tests || exit
          python3 -m pytest dag_tests.py -v || exit
          popd || exit
