name: Test Airflow DAGs

on:
  push:
    branches:
      - feature/dagbagtests

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.12' #Adjust version as needed.

      - name: Install dependencies
        run: pip install -r requirements.txt

      - name: Test DAGs with Pytest
        run: |
          pip install pytest==6.2.5
          pushd tests || exit
          python3 -m pytest test_dynamic_dags.py -v || exit
          popd || exit
