name: Upload Repo to GCS
on:
  push:
    branches:
      - "dev"
    paths:
      - "src/dags/**"


  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  if_merged:
    if: github.event.pull_request.merged == true
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.12'  # Replace with your desired Python version

      - name: Install dependencies (if any)
        run: |
          pip install -r requirements.txt  # Or your dependency management command

      - name: Replace {{PROJECT_ID}} in YAML files inside dags folder
        run: |
          PROJECT_ID="${{ vars.PROJECT_ID }}"
          find dags/ -name "*.yaml" -exec sed -i "s/{{PROJECT_ID}}/$PROJECT_ID/g" {} \;
