name: SQLFluff Lint

on:
  pull_request:
    types: [opened, synchronize, reopened]
    paths:
      - '**.sql'

jobs:
  lint:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.12'
          
      - name: Get changed SQL files
        id: changed_files
        run: |
          changed_sql_files=$(git diff --name-only HEAD~1 -- '*.sql')
          if [[ -n "$changed_sql_files" ]]; then
            echo "::set-output name=files::$changed_sql_files"
          fi

      - name: Lint SQL with SQLFluff
        if: steps.changed_files.outputs.files
        run: |
          pip install sqlfluff==0.9.1 click==8.0.3
          sqlfluff lint \
            --dialect bigquery \
            --ignore parsing,templating \
            --format github-annotation \
            --disable_progress_bar \
            ${{ steps.changed_files.outputs.files }} || exit 1
          popd || exit
