name: SQLFluff Lint

on:
  push:
    branches: [main]
    paths:
      - '**.sql' 
  pull_request:
    paths:
      - '**.sql' 
  merge_group: {}

jobs:
  lint:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        with:
          fetch-depth: ${{ github.event_name == 'pull_request' && 2 || 0 }}

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.12'
          

      - name: Run SQL Lint for modified files
        run: |
          pip install sqlfluff
          if [[ "${{ github.event_name }}" == 'pull_request' ]]; then
            changed_sql_files=$(git diff --name-only -r HEAD^1 HEAD -- '*.sql')
          else
            changed_sql_files=$(git diff --name-only ${{ github.event.before }} ${{ github.event.after }} -- '*.sql')
          fi
          
          sqlfluff lint \
            --dialect bigquery \
            --ignore parsing,templating \
            --format github-annotation \
            --disable_progress_bar \
            $changed_sql_files || exit 1
          
     
