name: SQLFluff Lint

on:
  pull_request:
    types: [opened, synchronize, reopened]
    paths:
      - '**.sql'

jobs:
  lint:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.12'

      - name: Lint SQL with SQLFluff
        run: |
          pip install sqlfluff
          pushd dags || exit
          sqlfluff fix sql/
          sqlfluff lint \
            --dialect bigquery \
            --ignore parsing,templating \
            --format github-annotation \
            --disable_progress_bar \
            sql/ || exit 1
          popd || exit

