name: SQLFluff Lint

on:
  pull_request:
    types: [opened, synchronize, reopened]
    paths:
      - '**.sql'

jobs:
  lint:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.12'
          
      - name: Get SQL changed files
        id: changed-sql-files
        uses: tj-actions/changed-files@v23
        with:
          files: |
            *.sql
            **/*.sql
      - name: Run if any of the listed files above is changed
        if: steps.changed-sql-files.outputs.any_changed == 'true'
        run: |
          pip install sqlfluff==0.9.1 click==8.0.3
          sqlfluff lint \
            --dialect bigquery \
            --ignore parsing,templating \
            --format github-annotation \
            --disable_progress_bar \
            ${{ steps.changed-sql-files.outputs.all_changed_files }} || exit 1
          
     
