name: Deploy DAGs to Dev Cloud Composer
on:
  push:
    branches:
      - "feature/ddltest"
    paths:
      - "dags/ddls/**.sql"

permissions:
  contents: read
  id-token: write

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Authenticate to Google Cloud
        uses: google-github-actions/auth@v2
        with:
          workload_identity_provider: "projects/818532436077/locations/global/workloadIdentityPools/composer-wif-dev/providers/github-uf"
          service_account: composer-test-sa@stock-data-ingess.iam.gserviceaccount.com
          create_credentials_file: true
          export_environment_variables: true
          cleanup_credentials: false

      - name: 'Set up Cloud SDK'
        uses: 'google-github-actions/setup-gcloud@v2'
        with:
          version: '>= 363.0.0'
      - name: BQ Table create
        run: |
          ddl_files=$(find dags/ddls -name "*.sql" | sort)

          for file in $ddl_files; do
            ddl_content=$(cat "$file")
            echo "Executing DDL: $file"

            if [[ "$ddl_content" == *'CREATE OR REPLACE TABLE'* ]]; then
              echo "ERROR: CREATE OR REPLACE TABLE detected in $file. This is not allowed in CICD deployments. Exiting."
              exit 1
            fi

            if [[ "$ddl_content" == *'CREATE TABLE'* ]]; then
              echo "Executing CREATE TABLE statement: $file"
              if ! bq query --use_legacy_sql=false < "$file"; then
                echo "Error executing CREATE TABLE: $file. Exiting."
                exit 1
              fi
            fi
          echo "DDL: $file executed successfully"
          done
