name: Deploy DAGs to Dev Cloud Composer
on:
  push:
    branches:
      - "feature/ddltest"
    paths:
      - "dags/ddls/**"

permissions:
  contents: read
  id-token: write

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Authenticate to Google Cloud
        uses: google-github-actions/auth@v2
        with:
          workload_identity_provider: "projects/818532436077/locations/global/workloadIdentityPools/composer-wif-dev/providers/github-uf"
          service_account: composer-test-sa@stock-data-ingess.iam.gserviceaccount.com
          create_credentials_file: true
          export_environment_variables: true
          cleanup_credentials: false
      - name: Sync Dags to GCS
        run: |
          echo "Hello"
